version: "3.8"
services:
  ### Postgres Database
#  postgres:
#    image: postgres:10.4
#    container_name: postgres
#    networks:
#      - rede
#    restart: always
#    ports:
#      - 5433:5432
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=db
  db:
    image: mysql:latest
    container_name: db
    networks:
      - rede
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ester
  ### API Spring Boot ###
  api:
    build: './'
    container_name: api
    depends_on:
      - db
    networks:
      - rede
    environment:
      - PORT=8080
      - DATABASE_HOST=db
      - DATABASE_NAME=ester
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=3306
    ports:
      - 8080:8080
volumes:
  db_data: {}
networks:
  rede:
    driver: bridge

